version: "2.3"

services:

  unprotected:
    image: approov/quickstart-nodejs-grpc-unprotected
    build:
      context: .
    environment:
      - DEBUG=hello-server
    env_file:
      - .env
    networks:
      - traefik
    command: sh -c "npm install && npm start"
    volumes:
      - ./unprotected-server:/home/node/workspace
      - ./.env:/home/node/workspace/.env
    labels:
      - "traefik.enable=true"
      # Override the container name in the generated name of the backend. Does not need to match the domain name.
      - "traefik.backend=unprotected-grpc.${BASE_PUBLIC_DOMAIN? Missing value for: BASE_PUBLIC_DOMAIN}"
      # The default docker network to be used by Traefik for connections to the container.
      - "traefik.docker.network=traefik"
      # Assign this frontend to entry point https. Overrides defaultEntryPoints.
      - "traefik.frontend.entryPoints=https"
      # The public host/domain name. Default: Host:{service}.{project_name}.{domain} when using docker-compose.
      - "traefik.frontend.rule=Host:unprotected-grpc.${BASE_PUBLIC_DOMAIN}"
      # The internal container port, not the public one that Traefik listens to.
      - "traefik.port=${GRPC_PORT:-50051}"
      # Override the default http protocol
      - "traefik.protocol=h2c"

  approov-token:
    image: approov/quickstart-nodejs-grpc-token-check
    build:
      context: .
    restart: always
    environment:
      - DEBUG=hello-server
    env_file:
      - .env
    networks:
      - traefik
    command: sh -c "npm install && npm start"
    volumes:
      - ./approov-protected-server/token-check:/home/node/workspace
      - ./.env:/home/node/workspace/.env
    labels:
      - "traefik.enable=true"
      # The container name in the generated name of the backend. Does not need to match the domain name.
      - "traefik.backend=token-grpc.${BASE_PUBLIC_DOMAIN? Missing value for: BASE_PUBLIC_DOMAIN}"
      # The default docker network to be used by Traefik for connections to the container.
      - "traefik.docker.network=traefik"
      # Assign this frontend to entry point https. Overrides defaultEntryPoints.
      - "traefik.frontend.entryPoints=https"
      # The public host/domain name. Default: Host:{service}.{project_name}.{domain} when using docker-compose.
      - "traefik.frontend.rule=Host:token-grpc.${BASE_PUBLIC_DOMAIN}"
      # The internal container port, not the public one that Traefik listens to.
      - "traefik.port=${GRPC_PORT:-50051}"
      # Override the default http protocol
      - "traefik.protocol=h2c"

  approov-token-binding:
    image: approov/quickstart-nodejs-grpc-token-binding-check
    build:
      context: .
    environment:
      - DEBUG=hello-server
    env_file:
      - .env
    networks:
      - traefik
    command: sh -c "npm install && npm start"
    volumes:
      - ./approov-protected-server/token-binding-check:/home/node/workspace
      - ./.env:/home/node/workspace/.env
    labels:
      - "traefik.enable=true"
      # The container name in the generated name of the backend. Does not need to match the domain name.
      - "traefik.backend=token-binding-grpc.${BASE_PUBLIC_DOMAIN? Missing value for: BASE_PUBLIC_DOMAIN}"
      # The default docker network to be used by Traefik for connections to the container.
      - "traefik.docker.network=traefik"
      # Assign this frontend to entry point https. Overrides defaultEntryPoints.
      - "traefik.frontend.entryPoints=https"
      # The public host/domain name. Default: Host:{service}.{project_name}.{domain} when using docker-compose.
      - "traefik.frontend.rule=Host:token-binding-grpc.${BASE_PUBLIC_DOMAIN}"
      # The internal container port, not the public one that Traefik listens to.
      - "traefik.port=${GRPC_PORT:-50051}"
      # Override the default http protocol
      - "traefik.protocol=h2c"

networks:
  traefik:
    external: true
